### ISSUE TITLE
Huggingface Accelerate

### ISSUE THREAD

**Issue by conceptofmind** [BlackSamorez/tensor_parallel#74]
Hi all,

Thank you for the great work.

I was wondering if this library was compatible with Huggingface `accelerate.prepare()` for training?

Thank you,

Enrico

**Comment by BlackSamorez** [comment]
Hi @conceptofmind,

No, the library is not compatible with `accelerate.prepare()` since it would be required to somehow integrate it on their side. Maybe it's possible, but I'd need to discuss with `accelerate` maintainers if that's a possibility.
For now I'm closing this issue but if anything comes out of it feel free to reopen it!
